# Generated by Django 4.1.5 on 2023-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_description_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(default='a;sdfjkas'),
            preserve_default=False,
        ),
    ]
